import 'package:flutter_sms/flutter_sms.dart';
import 'package:hifazat/globals.dart';

void _sendSMS(String message, List<String> recipents) async {
  String _result = await sendSMS(message: message, recipients: recipents)
      .catchError((onError) {
    print(onError);
  });
  print(_result);
}

void sendMessageToTrustedContacts() async {
  const message =
      "Hello, Please help me, I'm in danger.\n\n Auto generated by Hifazat. We've Heard a Scream.";

  for (var element in trustedContacts) {
    if (element.phoneNumber != null) {
      var phnNumber = element.phoneNumber!;
      _sendSMS(message, [phnNumber.number!]);
    }
  }
}
