import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_sms/flutter_sms.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:hifazat/globals.dart';
import 'package:hifazat/utils/location.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:geolocator/geolocator.dart';
import 'package:vibration/vibration.dart';


void _sendSMS(String message, List<String> recipents) async {
  String _result = await sendSMS(
    message: message,
    recipients: recipents,
    sendDirect: Platform.isAndroid,
  ).catchError((onError) {
    print(onError);
  });
  print(_result);
}

void sendMessageToTrustedContacts() async {
  if (!await Permission.sms.isGranted) {
    await Permission.sms.request();
  }
  if (await Permission.sms.isDenied) {
    SystemNavigator.pop();
  }

  Position pos = await determinePosition();

  String message =
      "Hello, Please help me, I'm in danger.\nMy Location: https://www.google.com/maps/search/?api=1&query=${pos.latitude},${pos.longitude} \n\n Auto generated by Hifazat. We've Heard a Scream.";

  for (var element in trustedContacts) {
    if (element.phoneNumber != null) {
      var phnNumber = element.phoneNumber!;
      _sendSMS(message, [phnNumber.number!]);
    }
  }

  var hasVibrator = await Vibration.hasVibrator();
  if (hasVibrator ?? false) {
    Vibration.vibrate(pattern: [500, 500, 500, 500]);
  }
  Fluttertoast.showToast(
      msg: "Sent SMS !",
      toastLength: Toast.LENGTH_SHORT,
  );
}
